[package]
name = "rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
atomic-wait = "1"
libc = "0.2.158"
readelf = "0.0.7"
tokio="1.40.0"

[profile.dev]
debug = true
